### ISSUE TITLE
eq3_v2: Feature Request: Use existing Temperature Sensor when Thermostat doesnt have one

### ISSUE THREAD

**Issue by TRon993** [ayufan/esphome-components#16]
Hi, 

im using this component for quite a while and am really happy with it. It works like a charm.

My Thermostats have as well no (usable) temperature sensor available but i do have at least one DHT22/BME280 Sensor connected to each of my esp32s. So i thought it would be nice to have the possibility to provide the available sensor data of a room to each eq3 thermostat.

Is there a way to let the user define a custom sensor to provide the current temperature in the room?

Thanks and BR

**Comment by ayufan** [comment]
The sensor will have to be connected locally to the ESP32 using `eq3_v2`. Currently, only this method is possible, as there's no way to "project" sensors from different places.

Ideally the best would be to buy a cheap Xiaomi BLE sensors, but the `eq3_v2` does not work with BLE as it requires kind of exclusive access to BLE stack due to stability aspects of BLE stack.

**Comment by TRon993** [comment]
Hi,

ok, thats not a problem. The temp sensors are directly connected to each esp32 that controls the rooms eq3 thermostat. So, how can i get the sensor data into the eq3 climate component?

Thanks for your reply! Appreciate that :)

**Comment by ayufan** [comment]
Here is your answer: https://github.com/ayufan/esphome-components/pull/2/files.

**Comment by TRon993** [comment]
Right on, thanks for the link.
How do i define that within esphome`s yaml?
```
sensor:
  - platform: dht
    pin: GPIO022
    model: dht22
    temperature:
      name: "${upper_devicename} Temperatur"
    humidity:
      name: "${upper_devicename} Luftfeuchte"

climate:
  - platform: eq3_v2
    id: eq3_${devicename}
    name: "${upper_devicename} EQ3"
    mac_address: 00:1A:22:06:F3:6C
    update_interval: 5min
    valve: # optional, allows to see valve state in %
      name: "${upper_devicename} EQ3 Ventil Status"
```

Thanks in advance!

**Comment by TRon993** [comment]
I assume that i probably need to define ids for the DHT22 Sensor to be used down below in
```
climate:
  - platform: eq3_v2
    id: eq3_${devicename}
    name: "${upper_devicename} EQ3"
    mac_address: 00:1A:22:06:F3:6C
    update_interval: 5min
    valve: # optional, allows to see valve state in %
      name: "${upper_devicename} EQ3 Ventil Status"
   temp: sensor.dht22.temp
```
when setting the id of "dht22.temp" for temperature?

**Comment by ayufan** [comment]
Likely something like this:

```yaml
sensor:
  - platform: dht
    pin: GPIO022
    model: dht22
    temperature:
      id: dht_temperature
      name: "${upper_devicename} Temperatur"
    humidity:
      name: "${upper_devicename} Luftfeuchte"

climate:
  - platform: eq3_v2
    id: eq3_${devicename}
    name: "${upper_devicename} EQ3"
    mac_address: 00:1A:22:06:F3:6C
    update_interval: 5min
    temperature_sensor: dht_temperature
    valve: # optional, allows to see valve state in %
      name: "${upper_devicename} EQ3 Ventil Status"
```
