### ISSUE TITLE
eq3_v2 component doesn't want to work

### ISSUE THREAD

**Issue by Wojcioo** [ayufan/esphome-components#21]
Hello
I'm trying to implement eq3_v2 component, but it doesn't want to compile in esphome because of the error "Platform not found: 'climate.eq3_v2'.
Here is part of my config:

```
esphome:
  name: esp32-eq3-gateway
  platform: ESP32
  board: esp32dev

logger:

api:

ota:

wifi:
  ssid: 'Home automation'
  password: 'secretpassword'

  ap:
    ssid: "Esp32-Eq3-Gateway"
    password: "password"

captive_portal:

web_server:
  port: 80
  
external_components:
  - source: github://ayufan/esphome-components

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: 03:14:54:0E:0A:5B
    name: "EQ3 valve"

time:
  - platform: sntp
    id: sntp_time
    
climate:
  - platform: eq3_v2
    id: office_eq3
    name: Bathroom EQ3
    mac_address: 03:14:54:0E:0A:5B
    update_interval: 30min
    valve:
      name: Bathroom EQ3 Valve State
      expire_after: 61min
```

I'm using ESPHome 2021.9.3.
Kind regards
