### ISSUE TITLE
Error trying to use the esp32_camera_web_server

### ISSUE THREAD

**Issue by yeyeto2788** [ayufan/esphome-components#22]
Hey @ayufan, 

First of all, thanks for this amazing components you've created, I tried to use the `esp32_camera_web_server` but I'm not able to finish compiling the code. Can you please help me a bit here? Maybe I'm doing something wrong 😢 

**Error output:**
```console
Processing garage_camera (board: esp32dev; framework: arduino; platform: platformio/espressif32@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
Library Manager: Installing Hash
Library Manager: Already installed, built-in library
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <AsyncTCP-esphome> 1.2.2
|   |-- <Crypto> 0.2.0
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <AsyncMqttClient-esphome> 0.8.4
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <noise-c> 0.1.3
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling .pioenvs/garage_camera/src/main.cpp.o
src/main.cpp:18:1: error: 'esp32_camera_web_server' does not name a type
 esp32_camera_web_server::WebServer *esp32_camera_web_server_webserver;
 ^
src/main.cpp: In function 'void setup()':
src/main.cpp:238:3: error: 'esp32_camera_web_server_webserver' was not declared in this scope
   esp32_camera_web_server_webserver = new esp32_camera_web_server::WebServer();
   ^
src/main.cpp:238:43: error: 'esp32_camera_web_server' does not name a type
   esp32_camera_web_server_webserver = new esp32_camera_web_server::WebServer();
                                           ^
src/main.cpp:240:47: error: 'esp32_camera_web_server' has not been declared
   esp32_camera_web_server_webserver->set_mode(esp32_camera_web_server::Stream);
                                               ^
Compiling .pioenvs/garage_camera/lib39c/noise-c/backend/sodium/dh-curve25519.c.o
Compiling .pioenvs/garage_camera/lib39c/noise-c/backend/sodium/hash-blake2b.c.o
Compiling .pioenvs/garage_camera/lib39c/noise-c/backend/sodium/hash-sha256.c.o
Compiling .pioenvs/garage_camera/lib39c/noise-c/crypto/aes/rijndael-alg-fst.c.o
/root/.platformio/lib/noise-c/src/backend/sodium/dh-curve25519.c: In function 'noise_curve25519_calculate':
/root/.platformio/lib/noise-c/src/backend/sodium/dh-curve25519.c:97:5: warning: ignoring return value of 'crypto_scalarmult_curve25519', declared with attribute warn_unused_result [-Wunused-result]
     crypto_scalarmult_curve25519(
     ^
Compiling .pioenvs/garage_camera/lib39c/noise-c/crypto/blake2/blake2b.c.o
Compiling .pioenvs/garage_camera/lib39c/noise-c/crypto/blake2/blake2s.c.o
Compiling .pioenvs/garage_camera/lib39c/noise-c/crypto/chacha/chacha.c.o
*** [.pioenvs/garage_camera/src/main.cpp.o] Error 1
```

**YAML used for the camera:**
```yaml
substitutions:
  # Common variables used on templates
  node_name: garage_camera
  update_interval: "5"
  log_level: debug
  # Get the secret's values
  node_ip: !secret garage_camera

# Include common packages in order not to rewrite every single node
packages:
  device_base: !include common/base_esp32.yaml

# Core configuration
esphome:
  name: ${node_name}
  board: esp32dev
  comment: "Garage monitoring camera"

esp32_camera:
  name: ${node_name} camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1600x1200
  jpeg_quality: 12

# Camera flash light
switch:
  - platform: gpio
    pin: GPIO4
    name: ${node_name} camera flash
    id: ${node_name}_camera_flash

external_components:
  - source: github://ayufan/esphome-components

esp32_camera_web_server:
  # define only what is needed
  # only a single stream is supported at a given time
  - port: 8080
    mode: stream
```

If you need more info just ask for it.

**Comment by yeyeto2788** [comment]
I just even tried to use external components like this:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/ayufan/esphome-components
      ref: master
```
But, no luck 😢
