### ISSUE TITLE
eq3 valve state without mqtt?

### ISSUE THREAD

**Issue by JamesT42** [ayufan/esphome-components#7]
Hi!
Is it possible to get the valve state without using mqtt?
Then your creation would be even better!
Thank you for your work
Cheers
James

**Comment by JamesT42** [comment]
Ok maybe uncommenting 
#expire_after: 11min
like this is enough?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Did you get it work without MQTT? 

I completely removed MQTT from my home assistant server, so I' would like to know this as well?

**Comment by ayufan** [comment]
Can you just test? The only requirement should be some kind of time service.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I will try when I have time and can report it back then 👍

**Comment by JamesT42** [comment]
Yes it works without MQTT, just uncomment or delete the line expire_after: ...

**Comment by h0jeZvgoxFepBQ2C** [comment]
Are there any sideeffects when commenting this line (even when you dont use mqtt)?

**Comment by ayufan** [comment]
Not really. I believe it is just a setting in config, but should not affect
the actual code.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ok, I have it running now and it works without MQTT 👍 

Is it normal that it doesn't transmit the measured temperature?

**Comment by ayufan** [comment]
No. It is not exposed

**Comment by JamesT42** [comment]
You can connect a temperature sensor to the esp32
example:

```
sensor:
  - platform: htu21d
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Humidity"
      id: humidity
    update_interval: 60s

i2c:
  sda: 21
  scl: 22
  scan: on
  #frequency: 400kHz

climate:
  - platform: eq3_v2
    id: eq3
    name: "EQ3"
    mac_address: 00:1AXX:XX:XX:XX
    update_interval: 5min
    temperature_sensor: temperature
    valve: # optional, allows to see valve state in %
      name: "EQ3 Valve"
```
