### ISSUE TITLE
eq3_v2: errors on compilation

### ISSUE THREAD

**Issue by disrupted** [ayufan/esphome-components#8]
receiving following errors during compilation:

```
INFO Reading configuration...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 03/28/21 02:00:00 to 10/31/21 03:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/eq3
Processing eq3 (platform: espressif32@1.6.0; framework: arduino; board: esp-wrover-kit)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp-wrover-kit.html
PLATFORM: Espressif 32 > Espressif ESP-WROVER-KIT
HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
DEBUG: CURRENT(ftdi) ON-BOARD(ftdi) EXTERNAL(esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <Preferences> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling /data/eq3/.pioenvs/eq3/src/esphome/components/climate/climate.cpp.o
Compiling /data/eq3/.pioenvs/eq3/src/esphome/components/climate/climate_mode.cpp.o
Compiling /data/eq3/.pioenvs/eq3/src/esphome/components/climate/climate_traits.cpp.o
Compiling /data/eq3/.pioenvs/eq3/src/esphome/components/eq3_v2/eq3.cpp.o
Compiling /data/eq3/.pioenvs/eq3/src/esphome/components/eq3_v2/eq3_cmd.cpp.o
Compiling /data/eq3/.pioenvs/eq3/src/esphome/components/esp32_ble_clients/esp32_ble.cpp.o
In file included from src/esphome/components/eq3_v2/eq3.cpp:3:0:
src/esphome/components/eq3_v2/eq3.cpp: In member function 'void EQ3Climate::parse_state(const string&)':
src/esphome/components/eq3_v2/eq3.cpp:169:58: error: 'hexencode' was not declared in this scope
hexencode((const uint8_t*)data.c_str(), data.size()).c_str());
^
src/esphome/core/log.h:119:86: note: in definition of macro 'esph_log_w'
esp_log_printf_(ESPHOME_LOG_LEVEL_WARN, tag, ESPHOME_LOG_FORMAT(tag, W, format), ##__VA_ARGS__)
^
src/esphome/components/eq3_v2/eq3.cpp:167:5: note: in expansion of macro 'ESP_LOGW'
ESP_LOGW(TAG, "State parse of %10llx failed: %s.",
^
src/esphome/components/eq3_v2/eq3.cpp: In member function 'void EQ3Climate::parse_schedule(const string&)':
src/esphome/components/eq3_v2/eq3.cpp:228:58: error: 'hexencode' was not declared in this scope
hexencode((const uint8_t*)data.c_str(), data.size()).c_str());
^
src/esphome/core/log.h:119:86: note: in definition of macro 'esph_log_w'
esp_log_printf_(ESPHOME_LOG_LEVEL_WARN, tag, ESPHOME_LOG_FORMAT(tag, W, format), ##__VA_ARGS__)
^
src/esphome/components/eq3_v2/eq3.cpp:226:5: note: in expansion of macro 'ESP_LOGW'
ESP_LOGW(TAG, "Schedule parse of %10llx failed: %s.",
^
src/esphome/components/eq3_v2/eq3.cpp: In member function 'void EQ3Climate::parse_id(const string&)':
src/esphome/components/eq3_v2/eq3.cpp:260:58: error: 'hexencode' was not declared in this scope
hexencode((const uint8_t*)data.c_str(), data.size()).c_str());
^
src/esphome/core/log.h:119:86: note: in definition of macro 'esph_log_w'
esp_log_printf_(ESPHOME_LOG_LEVEL_WARN, tag, ESPHOME_LOG_FORMAT(tag, W, format), ##__VA_ARGS__)
^
src/esphome/components/eq3_v2/eq3.cpp:258:5: note: in expansion of macro 'ESP_LOGW'
ESP_LOGW(TAG, "ID parse of %10llx failed: %s.",
^
src/esphome/components/eq3_v2/eq3.cpp:270:45: error: 'hexencode' was not declared in this scope
hexencode(id->serial, sizeof(id->serial)).c_str());
^
src/esphome/core/log.h:110:86: note: in definition of macro 'esph_log_i'
esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, ESPHOME_LOG_FORMAT(tag, I, format), ##__VA_ARGS__)
^
src/esphome/components/eq3_v2/eq3.cpp:269:3: note: in expansion of macro 'ESP_LOGI'
ESP_LOGI(TAG, "'%s': Serial: %s", get_name().c_str(),
^
src/esphome/components/eq3_v2/eq3.cpp: In member function 'virtual void EQ3Climate::dump_config()':
src/esphome/components/eq3_v2/eq3.cpp:288:45: error: 'LOG_CLIMATE' was not declared in this scope
LOG_CLIMATE("", "EQ3-Max Thermostat", this);
^
*** [/data/eq3/.pioenvs/eq3/src/esphome/components/eq3_v2/eq3.cpp.o] Error 1
In file included from src/esphome/components/eq3_v2/eq3_cmd.cpp:3:0:
src/esphome/components/eq3_v2/eq3_cmd.cpp: In member function 'void EQ3Climate::parse_client_notify(std::__cxx11::string)':
src/esphome/components/eq3_v2/eq3_cmd.cpp:289:58: error: 'hexencode' was not declared in this scope
hexencode((const uint8_t*)data.c_str(), data.size()).c_str());
^
src/esphome/core/log.h:119:86: note: in definition of macro 'esph_log_w'
esp_log_printf_(ESPHOME_LOG_LEVEL_WARN, tag, ESPHOME_LOG_FORMAT(tag, W, format), ##__VA_ARGS__)
^
src/esphome/components/eq3_v2/eq3_cmd.cpp:287:5: note: in expansion of macro 'ESP_LOGW'
ESP_LOGW(TAG, "Received unknown characteristic from %10llx: %s.",
^
*** [/data/eq3/.pioenvs/eq3/src/esphome/components/eq3_v2/eq3_cmd.cpp.o] Error 1
src/esphome/components/esp32_ble_clients/esp32_ble.cpp: In constructor 'ESP32BLE::ESP32BLE()':
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:30:61: error: 'ESP_LOGE' was not declared in this scope
ESP_LOGE(TAG, "esp_ble_gattc_register_callback: %x", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp: In member function 'bool ESP32BLE::ble_setup()':
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:50:17: error: 'btStarted' was not declared in this scope
if (btStarted()) {
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:64:52: error: 'ESP_LOGD' was not declared in this scope
ESP_LOGD(TAG, "esp_bt_controller_init: %d", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:70:54: error: 'ESP_LOGD' was not declared in this scope
ESP_LOGD(TAG, "esp_bt_controller_enable: %d", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:77:55: error: 'ESP_LOGE' was not declared in this scope
ESP_LOGE(TAG, "esp_bluedroid_init failed: %d", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:82:57: error: 'ESP_LOGE' was not declared in this scope
ESP_LOGE(TAG, "esp_bluedroid_enable failed: %d", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:91:67: error: 'ESP_LOGE' was not declared in this scope
ESP_LOGE(TAG, "esp_ble_gap_set_security_param failed: %d", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:96:56: error: 'ESP_LOGE' was not declared in this scope
ESP_LOGE(TAG, "esp_ble_gatt_set_local_mtu: %x", err);
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:101:12: error: 'delay' was not declared in this scope
delay(200);  // NOLINT
^
src/esphome/components/esp32_ble_clients/esp32_ble.cpp:103:32: error: 'ESP_LOGD' was not declared in this scope
ESP_LOGD(TAG, "BT init done.");
^
*** [/data/eq3/.pioenvs/eq3/src/esphome/components/esp32_ble_clients/esp32_ble.cpp.o] Error 1
========================== [ERROR] Took 2.15 seconds ==========================
```

my YAML for this project looks like this:
```yaml
esphome:
  name: eq3
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "<REDACTED>"
  password: "<REDACTED>"
  power_save_mode: none

# Enable logging
#logger:

# Enable Home Assistant API
#api:

ota:

# time is required by `eq3_v2` to send
# an accurate time spec when requesting
# current state
time:
  - platform: sntp
    id: sntp_time

# refresh component state every 30mins,
# and announce it to Home Assistant MQTT
climate:
  - platform: eq3_v2
    id: thermostat
    name: Thermostat
    mac_address: '<REDACTED>'
    update_interval: 30min
    valve: # optional, allows to save valve state in %
      name: Thermostat Valve State
      #expire_after: 61min

# allow to force refresh component state
switch:
  - platform: template
    name: "Refresh Thermostat"
    lambda: "return false;"
    turn_on_action:
      - component.update: thermostat
```
